### PR TITLE
Fix false positive resource leak report.

### PR DESCRIPTION
**Pull request by StormHub**
#308 #325

### CODE REVIEW

**Comment by StormHub** [comment]
@yyjdelete @caozhiyuan Please try the fix

**Comment by caozhiyuan** [comment]
@StormHub it's ok now

**Comment by yyjdelete** [comment]
@StormHub It works well.

Would you please also include the last 2 commit in the PR?
https://github.com/Azure/DotNetty/compare/dev...yyjdelete:test-308

**Comment by StormHub** [comment]
@yyjdelete added the debug assert align with netty.

**Pull request merged**
