### PR TITLE
Echo client-server example

### PR DESCRIPTION
**Pull request by Horusiath**
This is example of DotNetty client-server application. Server itself can be called using telnet. IMO missing parts are logging handler (which I havent found inside DotNetty implementation) and SSL support which is handled differently than using corellated netty examples.

### CODE REVIEW

**Comment by nayato** [comment]
@Horusiath, on SSL - have you seen TlsHandler? It's meant as SslHandler replacement based on SslStream. It's implemented differently but was meant to behave in the same way.

**Comment by Horusiath** [comment]
I've update example with SSL support.

**Comment by nayato** [comment]
Thanks! will surely review this tomorrow (PST)

**Comment by Horusiath** [comment]
I've updated the example with @nayato suggestions - only thing left is echo client printing out message echo'ed from server.

**Comment by nayato** [comment]
@Horusiath, LoggingHandler is a must in many situations especially with non-trivial pipeline composition so it will definitely be ported soon (#38). It actually provides nice looking bytebuf output + additional log for all the events. I'd say, that's how one should learn netty / DotNetty - by observing output from logging handler. Once that's in, we should use it in examples.

**Comment by nayato** [comment]
pls fix the commit message. I think we should move to netty style for this: http://netty.io/wiki/writing-a-commit-message.html

**Comment by nayato** [comment]
also, have you signed our CLA? https://cla.azure.com/

**Comment by azurecla** [comment]
__@Horusiath__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Pull request merged**
