### PR TITLE
InliningDiagnoser/Unsafe unaligned.

### PR DESCRIPTION
**Pull request by StormHub**
#371 Unsafe unaligned
#380 ThrowHelper
Added BenchmarkDotNet InliningDiagnoser
@yyjdelete I have changed all ThrowHelper not to do ldstr, you can test it out.

### CODE REVIEW

**Comment by yyjdelete** [comment]
@StormHub 
Consider not using `NoInlining` on the `ThrowXxx` method, that will prevent the runtime do some optimization with rarely branches(throw). See `https://github.com/dotnet/coreclr/pull/6103#issuecomment-234173671` for more info.

The others look good to me.

**Comment by yyjdelete** [comment]
```
```

**Comment by yyjdelete** [comment]
Edited: This maybe not really needed, since that make little difference in my computer. Modern CPU may use `Dynamic Branch Prediction` instead of static ones.

<details>
<summary>netcoreapp2.1(With `NoInlining`)</summary>

```asm
   377:             this.CheckIndex(index, 4);
00007FF98959D310 57                   push        rdi  
00007FF98959D311 56                   push        rsi  
00007FF98959D312 48 83 EC 28          sub         rsp,28h  
00007FF98959D316 48 8B F1             mov         rsi,rcx  
00007FF98959D319 8B FA                mov         edi,edx  
00007FF98959D31B 48 8B CE             mov         rcx,rsi  
00007FF98959D31E 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF98959D321 48 8B 80 00 01 00 00 mov         rax,qword ptr [rax+100h]  
00007FF98959D328 FF 50 08             call        qword ptr [rax+8]  //this.ReferenceCount
00007FF98959D32B 85 C0                test        eax,eax  
00007FF98959D32D 75 07                jne         00007FF98959D336  //jump
00007FF98959D32F 33 C9                xor         ecx,ecx  
00007FF98959D331 E8 FA D2 FE FF       call        00007FF98958A630  //ThrowHelper.ThrowIllegalReferenceCountException(0);
00007FF98959D336 48 8B CE             mov         rcx,rsi  
00007FF98959D339 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF98959D33C 48 8B 40 40          mov         rax,qword ptr [rax+40h]  
00007FF98959D340 FF 50 20             call        qword ptr [rax+20h]  //this.Capacity
00007FF98959D343 8B CF                mov         ecx,edi  
00007FF98959D345 83 C9 04             or          ecx,4  
00007FF98959D348 8D 57 04             lea         edx,[rdi+4]  
00007FF98959D34B 0B CA                or          ecx,edx  
00007FF98959D34D 2B C2                sub         eax,edx  
00007FF98959D34F 0B C8                or          ecx,eax  
00007FF98959D351 85 C9                test        ecx,ecx  //MathUtil.IsOutOfBounds(,,)
00007FF98959D353 7D 1C                jge         00007FF98959D371  //jump
00007FF98959D355 48 8B CE             mov         rcx,rsi  
00007FF98959D358 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF98959D35B 48 8B 40 40          mov         rax,qword ptr [rax+40h]  
00007FF98959D35F FF 50 20             call        qword ptr [rax+20h]  //this.Capacity
00007FF98959D362 44 8B C0             mov         r8d,eax  
00007FF98959D365 8B CF                mov         ecx,edi  
00007FF98959D367 BA 04 00 00 00       mov         edx,4  
00007FF98959D36C E8 5F D2 FE FF       call        00007FF98958A5D0  //ThrowHelper.ThrowIndexOutOfRangeException_Index
   378:             return this._GetInt(index);
00007FF98959D371 48 8B CE             mov         rcx,rsi  
00007FF98959D374 8B D7                mov         edx,edi  
00007FF98959D376 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF98959D379 48 8B 40 68          mov         rax,qword ptr [rax+68h]  
00007FF98959D37D 48 8B 40 28          mov         rax,qword ptr [rax+28h]  
00007FF98959D381 48 83 C4 28          add         rsp,28h  
00007FF98959D385 5E                   pop         rsi  
00007FF98959D386 5F                   pop         rdi  
00007FF98959D387 48 FF E0             jmp         rax  
```
</details>
<details>
<summary>netcoreapp2.1(Without `NoInlining`)</summary>

```asm
   377:             this.CheckIndex(index, 4);
00007FF989556B10 57                   push        rdi  
00007FF989556B11 56                   push        rsi  
00007FF989556B12 48 83 EC 28          sub         rsp,28h  
00007FF989556B16 48 8B F9             mov         rdi,rcx  
00007FF989556B19 8B F2                mov         esi,edx  
00007FF989556B1B 48 8B CF             mov         rcx,rdi  
00007FF989556B1E 48 8B 07             mov         rax,qword ptr [rdi]  
00007FF989556B21 48 8B 80 00 01 00 00 mov         rax,qword ptr [rax+100h]  
00007FF989556B28 FF 50 08             call        qword ptr [rax+8]  //this.ReferenceCount
00007FF989556B2B 85 C0                test        eax,eax  
00007FF989556B2D 74 38                je          00007FF989556B67  //fallthrough
00007FF989556B2F 48 8B CF             mov         rcx,rdi  
00007FF989556B32 48 8B 07             mov         rax,qword ptr [rdi]  
00007FF989556B35 48 8B 40 40          mov         rax,qword ptr [rax+40h]  
00007FF989556B39 FF 50 20             call        qword ptr [rax+20h]  //this.Capacity
00007FF989556B3C 8B CE                mov         ecx,esi  
00007FF989556B3E 83 C9 04             or          ecx,4  
00007FF989556B41 8D 56 04             lea         edx,[rsi+4]  
00007FF989556B44 0B CA                or          ecx,edx  
00007FF989556B46 2B C2                sub         eax,edx  
00007FF989556B48 0B C8                or          ecx,eax  
00007FF989556B4A 85 C9                test        ecx,ecx  //MathUtil.IsOutOfBounds(,,)
00007FF989556B4C 7C 20                jl          00007FF989556B6E  //fallthrough
   378:             return this._GetInt(index);
00007FF989556B4E 48 8B CF             mov         rcx,rdi  
00007FF989556B51 8B D6                mov         edx,esi  
00007FF989556B53 48 8B 07             mov         rax,qword ptr [rdi]  
00007FF989556B56 48 8B 40 68          mov         rax,qword ptr [rax+68h]  
00007FF989556B5A 48 8B 40 28          mov         rax,qword ptr [rax+28h]  
00007FF989556B5E 48 83 C4 28          add         rsp,28h  
00007FF989556B62 5E                   pop         rsi  
00007FF989556B63 5F                   pop         rdi  
00007FF989556B64 48 FF E0             jmp         rax  
   377:             this.CheckIndex(index, 4);
00007FF989556B67 33 C9                xor         ecx,ecx  
00007FF989556B69 E8 9A 2C FF FF       call        00007FF989549808  //ThrowHelper.ThrowIllegalReferenceCountException(0)
00007FF989556B6E 48 8B CF             mov         rcx,rdi  
00007FF989556B71 48 8B 07             mov         rax,qword ptr [rdi]  
00007FF989556B74 48 8B 40 40          mov         rax,qword ptr [rax+40h]  
00007FF989556B78 FF 50 20             call        qword ptr [rax+20h]  //this.Capacity
00007FF989556B7B 44 8B C0             mov         r8d,eax  
00007FF989556B7E 8B CE                mov         ecx,esi  
00007FF989556B80 BA 04 00 00 00       mov         edx,4  
00007FF989556B85 E8 1E 2C FF FF       call        00007FF9895497A8  //ThrowHelper.ThrowIndexOutOfRangeException_Index
00007FF989556B8A CC                   int         3  
```
</details>
<details>
<summary>netcoreapp1.1(With `NoInlining`)</summary>

```asm
   377:             this.CheckIndex(index, 4);
00007FF9895BD330 57                   push        rdi  
00007FF9895BD331 56                   push        rsi  
00007FF9895BD332 48 83 EC 28          sub         rsp,28h  
00007FF9895BD336 48 8B F1             mov         rsi,rcx  
00007FF9895BD339 8B FA                mov         edi,edx  
00007FF9895BD33B 48 8B CE             mov         rcx,rsi  
00007FF9895BD33E 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF9895BD341 48 8B 80 00 01 00 00 mov         rax,qword ptr [rax+100h]  
00007FF9895BD348 FF 50 08             call        qword ptr [rax+8]  //this.ReferenceCount
00007FF9895BD34B 85 C0                test        eax,eax  
00007FF9895BD34D 74 54                je          00007FF9895BD3A3  //fallthrough
00007FF9895BD34F 48 8B CE             mov         rcx,rsi  
00007FF9895BD352 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF9895BD355 48 8B 40 40          mov         rax,qword ptr [rax+40h]  
00007FF9895BD359 FF 50 20             call        qword ptr [rax+20h]  //this.Capacity
00007FF9895BD35C 8B CF                mov         ecx,edi  
00007FF9895BD35E 83 C9 04             or          ecx,4  
00007FF9895BD361 8D 57 04             lea         edx,[rdi+4]  
00007FF9895BD364 0B CA                or          ecx,edx  
00007FF9895BD366 2B C2                sub         eax,edx  
00007FF9895BD368 0B C8                or          ecx,eax  
00007FF9895BD36A 85 C9                test        ecx,ecx  //MathUtil.IsOutOfBounds(,,)
00007FF9895BD36C 7D 1C                jge         00007FF9895BD38A  //jump
00007FF9895BD36E 48 8B CE             mov         rcx,rsi  
00007FF9895BD371 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF9895BD374 48 8B 40 40          mov         rax,qword ptr [rax+40h]  
00007FF9895BD378 FF 50 20             call        qword ptr [rax+20h]  //this.Capacity
00007FF9895BD37B 44 8B C0             mov         r8d,eax  
00007FF9895BD37E 8B CF                mov         ecx,edi  
00007FF9895BD380 BA 04 00 00 00       mov         edx,4  
00007FF9895BD385 E8 46 D2 FE FF       call        00007FF9895AA5D0  //ThrowHelper.ThrowIndexOutOfRangeException_Index
   378:             return this._GetInt(index);
00007FF9895BD38A 48 8B CE             mov         rcx,rsi  
00007FF9895BD38D 8B D7                mov         edx,edi  
00007FF9895BD38F 48 8B 06             mov         rax,qword ptr [rsi]  
00007FF9895BD392 48 8B 40 68          mov         rax,qword ptr [rax+68h]  
00007FF9895BD396 48 8B 40 28          mov         rax,qword ptr [rax+28h]  
00007FF9895BD39A 48 83 C4 28          add         rsp,28h  
00007FF9895BD39E 5E                   pop         rsi  
00007FF9895BD39F 5F                   pop         rdi  
00007FF9895BD3A0 48 FF E0             jmp         rax  
   377:             this.CheckIndex(index, 4);
00007FF9895BD3A3 33 C9                xor         ecx,ecx  
00007FF9895BD3A5 E8 86 D2 FE FF       call        00007FF9895AA630  //ThrowHelper.ThrowIllegalReferenceCountException(0)
00007FF9895BD3AA CC                   int         3  
```
</details>
Seems `ThrowIndexOutOfRangeException_Index/ReaderIndex/WriterIndex` are too long to be recognized in `netcoreapp1.1`, an workaround is don't use param capture in the local functions, and call with params directly.

**Comment by StormHub** [comment]
@yyjdelete see https://github.com/mikedn/coreclr/blob/e3c3330339630f967bdb27c6bcde089e787b2aeb/tests/src/JIT/Performance/CodeQuality/Inlining/NoThrowInline.cs#L36

**Comment by yyjdelete** [comment]
Not sure what do you want to say? But `ThrowArgumentNullException` is not marked as `MethodImplOptions.NoInlining` here.

**Comment by StormHub** [comment]
@yyjdelete It does not matter much at the moment.

**Comment by yyjdelete** [comment]
+1

**Pull request merged**
