### PR TITLE
Follow up .NET tooling/upgraded packages to latest stable version

### PR DESCRIPTION
**Pull request by StormHub**
1. Microsoft.Extensions.Configuration from 1.1.0 to 1.1.1
2. Microsoft.Extensions.Logging from 1.1.0 to 1.1.1
3. Google.Protobuf from 3.1.0 to 3.2.0
4. Microsoft.NET.Test.Sdk from 15.0.0 preview to 15.0.0
5. XUnit to 2.2.0 release
6. Moq from alpha to 4.7.1
7. NBench from 0.3.4 to 1.0.0

### CODE REVIEW

**Comment by nayato** [comment]
@StormHub per build something's not right about NBench. I think you should update build script as well to get the latest runner as well

**Comment by StormHub** [comment]
Upgraded NBench.Runner to 1.0.0

**Comment by StormHub** [comment]
hum, bench runner is not running

**Comment by nayato** [comment]
pls try locally with `powershell .\build.ps1 -target=Benchmark`

**Comment by StormHub** [comment]
Found the problem, nbench requires NET452, it was the wrong directory.

**Comment by StormHub** [comment]
Now it works!

**Comment by StormHub** [comment]
I had an old NET45 sitting there so didn't notice the problem.

**Comment by yyjdelete** [comment]
@StormHub 

Found all the unit tests for net45 is skiped now.
```
[xUnit.net 00:00:00.1107875] Skipping: DotNetty.Tests.Common (Could not find any of the following assemblies: xunit.execution.desktop.dll)
No test is available in C:\projects\dotnetty\test\DotNetty.Tests.Common\bin\Release\net45\win-x64\DotNetty.Tests.Common.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```
https://github.com/xunit/xunit/issues/1130 say that `The minimum version of .NET required for desktop CLR unit tests is now .NET 4.5.2.` since xunit 2.2.0. The last version works for net45 is `2.2.0-beta5-*`/`2.1.0`.


And not sure if it's also needed to update `appveyor.yaml` from `image: Visual Studio 2017 RC` to `image: Visual Studio 2017` as a part of SDK update.

**Comment by StormHub** [comment]
@yyjdelete It is running on netcoreapp, let me try reset to net452 and see what happens.

**Comment by StormHub** [comment]
I suppose we have to get all unit tests to net452, I have changed the performance one to 452 since NBench explicitly saying only support net452.

**Comment by StormHub** [comment]
@yyjdelete PR #229, changed all unit test projects to NET452 and xunit running correctly.

**Pull request merged**
