### PR TITLE
Downgraded to net45

### PR DESCRIPTION
**Pull request by alexvaluyskiy**
Moved all libraries, tests and examples to net45 from net451

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexvaluyskiy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@alexvaluyskiy__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by nayato** [comment]
@alexvaluyskiy could you pls follow up on build failure?

**Comment by nayato** [comment]
@alexvaluyskiy reproed with a second build as well

**Comment by alexvaluyskiy** [comment]
@nayato Have no idea why it is failing. Works fine locally

**Comment by nayato** [comment]
Considering tests fail under .net core, I suspect it has more to do with upgrade to new version rather than with your changes.

**Comment by nayato** [comment]
actually in previous runs there were failures on both core 1.1 and 4.5.

**Pull request merged**
